name: "New VFS team member"
description: "This is just an example, not actually in use anywhere."
title: "New VFS Team Member Template Your name here"
labels: ["platform-orientation", "new-vfs-team-member", "platform-tech-team-support"]
assignees: 
  - shiragoodman
body:
  - type: input
    id: your-name
    attributes:
      label: Your name
      description: This is where your name goes
    validations:
      required: true
  - type: markdown
    attributes:
      value: "Here's some extra instructions, plus a [link to useful information](https://va.gov)."
  - type: dropdown
    id: ice-cream-flavor
    attributes:
      label: What's your favorite ice cream flavor?
      options:
        - Vanilla
        - Chocolate
        - Strawberry
        - Other
    validations:
      required: true
  - type: checkboxes
    id: ice-cream-meals
    attributes:
      label: At which meal(s) will you eat ice cream today?
      description: You can choose more than one.
      options:
        - label: Breakfast
        - label: Lunch
        - label: Dinner
