name: "New VFS team member"
description: "New VFS team members fill out this form."
title: "New VFS Team Member Template Your name here"
labels: ["platform-orientation", "new-vfs-team-member", "platform-tech-team-support"]
body:
  - type: markdown
    attributes:
      value: "## Welcome and introduction"
  - type: markdown
    attributes:
      value: "[ ] Welcome to the Department of Veterans Affairs (VA) Veteran Facing Services (VFS) team."
  - type: markdown
    attributes:
      value: "The tasks on this list are designed to provide you with access to technologies, and maintain professional and legal compliance between VA.gov and its various contractors."
  - type: markdown
    attributes:
      value: "Complete the form and tasks then click create."
  - type: markdown
    attributes:
      value: "### All"
  - type: checkboxes
    id: all
    attributes:
      label: Add your name to the ticket title
      options:
        - label: Complete
  - type: markdown
    attributes:
      value: "[ ] Add your name to the ticket title"
  - type: input
    id: your-name
    attributes:
      label: Your name
    validations:
      required: true
  - type: input
    id: pronouns
    attributes:
      label: Pronouns
      description: (e.g. she/her)
    validations:
      required: false
  - type: input
    id: role
    attributes:
      label: Role
    validations:
      required: true
  - type: input
    id: email
    attributes:
      label: Email
    validations:
      required: true
  - type: input
    id: GitHubhandle
    attributes:
      label: GitHub handle
      description: Providing your GitHub handle will allow Platform to provide you access to the necessary GitHub repos.
    validations:
      required: true
  - type: input
    id: startdate
    attributes:
      label: Start date
    validations:
      required: true
  - type: input
    id: vfsteam
    attributes:
      label: VFS team
    validations:
      required: true
  - type: checkboxes
    attributes:
      label: Code of Conduct
      description: The Code of Conduct helps create a safe space for everyone. We require that everyone agrees to it [Code of Conduct](https://github.com/allison0034/testyaml/edit/main/.github/ISSUE_TEMPLATE/new-vfs-team-member.yml).
      options:
        - label: I agree to follow this project's [Code of Conduct](https://github.com/allison0034/testyaml/edit/main/.github/ISSUE_TEMPLATE/new-vfs-team-member.yml)
          required: true
