name: "New VFS team member"
description: "New VFS team members fill out this form."
title: "New VFS Team Member Template Your name here"
labels: ["platform-orientation", "new-vfs-team-member", "platform-tech-team-support"]
body:
  - type: markdown
    attributes:
      value: "## Welcome and introduction"
  - type: markdown
    attributes:
      value: "Welcome to the Department of Veterans Affairs (VA) Veteran Facing Services (VFS) team."
  - type: markdown
    attributes:
      value: "The tasks on this list are designed to provide you with access to technologies, and maintain professional and legal compliance between VA.gov and its various contractors."
  - type: markdown
    attributes:
      value: "Complete the form and tasks then click create."
  - type: markdown
    attributes:
      value: "**Note:** this ticket should not be submitted/created until after you receive access to the appropriate repos. You will receive an email titled “USAccess PIV Sponsored” when your access is ready."
  - type: markdown
    attributes:
      value: "### All"
  - type: checkboxes
    id: all
    attributes:
      label: Ticket title
      options:
        - label: Add your name to the ticket title
  - type: input
    id: your-name
    attributes:
      label: Your name
    validations:
      required: true
  - type: input
    id: pronouns
    attributes:
      label: Pronouns
      description: (e.g. she/her)
    validations:
      required: false
  - type: input
    id: role
    attributes:
      label: Role
    validations:
      required: true
  - type: input
    id: email
    attributes:
      label: Email
    validations:
      required: true
  - type: input
    id: GitHubhandle
    attributes:
      label: GitHub handle
      description: Providing your GitHub handle will allow Platform to provide you access to the necessary GitHub repos.
    validations:
      required: true
  - type: input
    id: startdate
    attributes:
      label: Start date
    validations:
      required: true
  - type: input
    id: vfsteam
    attributes:
      label: VFS team
    validations:
      required: true
  - type: checkboxes
    attributes:
      label: Slack profile
      description: 
      options:
        - label: Update your [Slack profile](https://depo-platform-documentation.scrollhelp.site/getting-started/slack-profile)
  - type: checkboxes
    attributes:
      label: Access to tools
      description:
      options:
        - label: Request [access to tools](https://depo-platform-documentation.scrollhelp.site/getting-started/Request-access-to-tools.969605215.html)
  - type: checkboxes
    attributes:
      label: Confirm access
      description: **Note** Membership in the VA Github Organization is a prerequisite for getting access to `vets.gov-write` and access to many commonly-used repositories. Platform will not be able to complete this task if you are not a member of the VA GitHub Organization.
      options:
        - label: Confirm that you have access to the [VA GitHub Organization](https://depo-platform-documentation.scrollhelp.site/getting-started/request-access-to-tools#Requestaccesstotools-GettingaccesstotheVAGitHuborganization)
  - type: checkboxes
    attributes:
      label: Opt out of Google Analytics on all of your browsers on your work machines, personal machines (if you are not a Veteran yourself using the site for your own applications), and mobile devices
      description: Go to [Opt out of Google Analytics](https://www.va.gov/analytics-opt-out.html)
      options:
        - label: Complete
  - type: checkboxes
    attributes:
      label: Are you a Veteran?
      description: Consider adding your name to the [Veterans willing to help VA teams with product testing](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/Administrative/vagov-users/team-veterans.md) document
      options:
        - label: Complete
  - type: markdown
    attributes:
      value: "### Practice area specific"
  - type: markdown
    attributes:
      value: "#### Front-end and back-end Engineers"
  - type: checkboxes
    attributes:
      label: Confirm that You Can Log In as a Test User
      description: Go to [Confirm that You Can Log In as a Test User](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/Administrative/accessing-staging.md)
      options:
        - label: Complete
  - type: markdown
    attributes:
      value: "#### Product Managers & Delivery Managers"
  - type: checkboxes
    attributes:
      label: Schedule a PM intro via Calendly with Shira Goodman (Platform Governance Team PM)
      description: Go to [Calendly](https://calendly.com/collaboration-cycle/product-manager-intro)
      options:
        - label: Complete
  - type: checkboxes
    attributes:
      label: If your team is new, please complete the New VFS Team ticket
      description: Go to [Calendly](https://calendly.com/collaboration-cycle/product-manager-intro)
      options:
        - label: If your team is new, please complete the [New VFS Team ticket](https://depo-platform-documentation.scrollhelp.site/getting-started/guidance-for-new-teams-and-team-members#Guidancefornewteamsandteammembers-NewVFSteams). If you're joining an existing team, you can skip this step.
