name: "New VFS team member2"
description: "New VFS team members fill out this form."
title: "New VFS Team Member Template Your name here2"
labels: ["platform-orientation", "new-vfs-team-member", "platform-tech-team-support"]
body:
  - type: markdown
    attributes:
      value: "## Welcome and introduction"
  - type: markdown
    attributes:
      value: "Welcome to the Department of Veterans Affairs (VA) Veteran Facing Services (VFS) team."
  - type: markdown
    attributes:
      value: "The tasks on this list are designed to provide you with access to technologies, and maintain professional and legal compliance between VA.gov and its various contractors."
  - type: markdown
    attributes:
      value: "Complete the form and tasks then click create."
  - type: markdown
    attributes:
      value: "**Note:** this ticket should not be submitted/created until after you receive access to the appropriate repos. You will receive an email titled “USAccess PIV Sponsored” when your access is ready."
  - type: markdown
    attributes:
      value: "### All"
  - type: input
    id: your-name
    attributes:
      label: Your name
    validations:
      required: true
  - type: input
    id: pronouns
    attributes:
      label: Pronouns
      description: (e.g. she/her)
    validations:
      required: false
  - type: input
    id: role
    attributes:
      label: Role
    validations:
      required: true
  - type: input
    id: email
    attributes:
      label: Email
    validations:
      required: true
  - type: input
    id: GitHubhandle
    attributes:
      label: GitHub handle
      description: Providing your GitHub handle will allow Platform to provide you access to the necessary GitHub repos.
    validations:
      required: true
  - type: input
    id: startdate
    attributes:
      label: Start date
    validations:
      required: true
  - type: input
    id: vfsteam
    attributes:
      label: VFS team
    validations:
      required: true
